name: wemystic
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: any
  google_sign_in: any
  shared_preferences: any
  flutter_secure_storage: any
  flutter_facebook_login: any
  package_info: any
  cloud_firestore: any
  firebase_analytics:
  intl: any
  flutter_webview_plugin:
  flutter_html_view: any
  cached_network_image: ^0.4.0
  carousel_pro: ^0.0.1
  firebase_messaging:
  url_launcher: ^4.0.1
  share: ^0.5.3
  flutter_date_picker: ^0.1.2
  datetime_picker_formfield: ^0.1.7
  flutter_cupertino_date_picker: ^0.2.0

dependency_overrides:
  http: any
  flutter_cache_manager: ^0.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  uuid: ^1.0.3
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - images/icon_check.png
    - images/icon_facebook.png
    - images/icon_googleplus.png
    - images/icon_horoscope_health.png
    - images/icon_horoscope_love.png
    - images/icon_horoscope_money.png
    - images/icon_nav_account.png
    - images/icon_nav_astrology.png
    - images/icon_nav_birthchart.png
    - images/icon_nav_home.png
    - images/loading_icon.png
    - images/logo_color.png
    - images/logo_white.png
    - images/logo_white_2x.png
    - images/slogan_color.png
    - images/slogan_white.png
    - images/loading_page_icons.gif
    - images/zodiac/icon_zodiac_color_aquarius.png
    - images/zodiac/icon_zodiac_color_aries.png
    - images/zodiac/icon_zodiac_color_cancer.png
    - images/zodiac/icon_zodiac_color_capricorn.png
    - images/zodiac/icon_zodiac_color_gemini.png
    - images/zodiac/icon_zodiac_color_leo.png
    - images/zodiac/icon_zodiac_color_libra.png
    - images/zodiac/icon_zodiac_color_pisces.png
    - images/zodiac/icon_zodiac_color_sagittarius.png
    - images/zodiac/icon_zodiac_color_scorpio.png
    - images/zodiac/icon_zodiac_color_taurus.png
    - images/zodiac/icon_zodiac_color_virgo.png
    - images/zodiac/icon_zodiac_white_aquarius.png
    - images/zodiac/icon_zodiac_white_aries.png
    - images/zodiac/icon_zodiac_white_cancer.png
    - images/zodiac/icon_zodiac_white_capricorn.png
    - images/zodiac/icon_zodiac_white_gemini.png
    - images/zodiac/icon_zodiac_white_leo.png
    - images/zodiac/icon_zodiac_white_libra.png
    - images/zodiac/icon_zodiac_white_pisces.png
    - images/zodiac/icon_zodiac_white_sagittarius.png
    - images/zodiac/icon_zodiac_white_scorpio.png
    - images/zodiac/icon_zodiac_white_taurus.png
    - images/zodiac/icon_zodiac_white_virgo.png
    - images/i_zodiac/i_aquarius.png
    - images/i_zodiac/i_aries.png
    - images/i_zodiac/i_cancer.png
    - images/i_zodiac/i_capricorn.png
    - images/i_zodiac/i_gemini.png
    - images/i_zodiac/i_leo.png
    - images/i_zodiac/i_libra.png
    - images/i_zodiac/i_pisces.png
    - images/i_zodiac/i_sagittarius.png
    - images/i_zodiac/i_scorpio.png
    - images/i_zodiac/i_taurus.png
    - images/i_zodiac/i_virgo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
